server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDB
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create # create tables on startup
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client: # Eureka Client Configuration
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/